# Create target folder
mkdir -p assets/disco
# Download each image
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/7/7d/Portrait_abigail.png -O assets/disco/Portrait_abigail.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/0/01/Portrait_acele.png -O assets/disco/Portrait_acele.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/3/3e/Portrait_alain.png -O assets/disco/Portrait_alain.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/0/01/Portrait_aliiz.png -O assets/disco/Portrait_aliiz.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/e/e0/Portrait_andre.png -O assets/disco/Portrait_andre.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/b/b1/Portrait_annete.png -O assets/disco/Portrait_annete.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/3/3b/Portrait_babe.png -O assets/disco/Portrait_babe.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/5/53/Portrait_bloated-corpse.png -O assets/disco/Portrait_bloated-corpse.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/7/74/Portrait_chester.png -O assets/disco/Portrait_chester.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/7/71/Portrait_cindy.png -O assets/disco/Portrait_cindy.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/c/cf/Portrait_cleaning-lady.png -O assets/disco/Portrait_cleaning-lady.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/c/c3/Portrait_cook.png -O assets/disco/Portrait_cook.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/d/df/Portrait_crypto.png -O assets/disco/Portrait_crypto.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/d/d1/Portrait_cuno.png -O assets/disco/Portrait_cuno.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/c/cb/Portrait_cunoesse.png -O assets/disco/Portrait_cunoesse.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/7/7b/Portrait_cunos-dad.png -O assets/disco/Portrait_cunos-dad.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/e/e3/Portrait_de-paule.png -O assets/disco/Portrait_de-paule.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/9/93/Portrait_deserter.png -O assets/disco/Portrait_deserter.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/a/a0/Portrait_dicemaker.png -O assets/disco/Portrait_dicemaker.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/5/55/Portrait_djmesh.png -O assets/disco/Portrait_djmesh.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/1/1f/Portrait_egg-head_-92794.png -O assets/disco/Portrait_egg-head_-92794.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/f/f3/Portrait_egg-head.png -O assets/disco/Portrait_egg-head.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/0/0f/Portrait_eugene.png -O assets/disco/Portrait_eugene.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/9/95/Portrait_evrart.png -O assets/disco/Portrait_evrart.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/4/41/Portrait_fat-angus.png -O assets/disco/Portrait_fat-angus.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/a/a1/Portrait_flacio.png -O assets/disco/Portrait_flacio.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/c/c3/Portrait_flaubert.png -O assets/disco/Portrait_flaubert.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/b/bc/Portrait_fritte.png -O assets/disco/Portrait_fritte.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/b/b4/Portrait_ftw.png -O assets/disco/Portrait_ftw.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/6/62/Portrait_gardener.png -O assets/disco/Portrait_gardener.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/c/c7/Portrait_garte.png -O assets/disco/Portrait_garte.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/4/40/Portrait_gaston.png -O assets/disco/Portrait_gaston.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/d/d6/Portrait_glen.png -O assets/disco/Portrait_glen.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/5/51/Portrait_hanged.png -O assets/disco/Portrait_hanged.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/f/f8/Portrait_jean.png -O assets/disco/Portrait_jean.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/b/be/Portrait_joyce.png -O assets/disco/Portrait_joyce.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/7/74/Portrait_jules.png -O assets/disco/Portrait_jules.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/2/21/Portrait_kitsuragi_bj.png -O assets/disco/Portrait_kitsuragi_bj.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/9/94/Portrait_kitsuragi.png -O assets/disco/Portrait_kitsuragi.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/6/69/Portrait_klaasje.png -O assets/disco/Portrait_klaasje.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/f/f6/Portrait_kortenaer.png -O assets/disco/Portrait_kortenaer.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/1/15/Portrait_lena.png -O assets/disco/Portrait_lena.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/9/94/Portrait_leo.png -O assets/disco/Portrait_leo.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/8/86/Portrait_librarian.png -O assets/disco/Portrait_librarian.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/1/17/Portrait_liliennes-other-twin.png -O assets/disco/Portrait_liliennes-other-twin.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/2/2a/Portrait_liliennes-twin.png -O assets/disco/Portrait_liliennes-twin.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/0/06/Portrait_little-lily.png -O assets/disco/Portrait_little-lily.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/6/64/Portrait_man-with-sunglasses.png -O assets/disco/Portrait_man-with-sunglasses.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/8/86/Portrait_manana.png -O assets/disco/Portrait_manana.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/2/2d/Portrait_manonwaterlock.png -O assets/disco/Portrait_manonwaterlock.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/4/4e/Portrait_measurehead.png -O assets/disco/Portrait_measurehead.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/f/f6/Portrait_mikael.png -O assets/disco/Portrait_mikael.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/2/22/Portrait_Minot.png -O assets/disco/Portrait_Minot.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/d/df/Portrait_morell.png -O assets/disco/Portrait_morell.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/3/34/Portrait_netpicker.png -O assets/disco/Portrait_netpicker.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/1/1d/Portrait_nix-gottlieb.png -O assets/disco/Portrait_nix-gottlieb.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/a/a5/Portrait_noid.png -O assets/disco/Portrait_noid.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/9/93/Portrait_paledriver.png -O assets/disco/Portrait_paledriver.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/9/98/Portrait_pigs.png -O assets/disco/Portrait_pigs.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/0/0c/Portrait_plaisance.png -O assets/disco/Portrait_plaisance.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/1/19/Portrait_racist.png -O assets/disco/Portrait_racist.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/4/45/Portrait_real-estate-agent.png -O assets/disco/Portrait_real-estate-agent.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/1/15/Portrait_rene.png -O assets/disco/Portrait_rene.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/d/dc/Portrait_repeater-station.png -O assets/disco/Portrait_repeater-station.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/d/d6/Portrait_rosemary.png -O assets/disco/Portrait_rosemary.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/1/1a/Portrait_roy.png -O assets/disco/Portrait_roy.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/5/5e/Portrait_ruby.png -O assets/disco/Portrait_ruby.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/f/f1/Portrait_ruud.png -O assets/disco/Portrait_ruud.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/3/33/Portrait_scablead.png -O assets/disco/Portrait_scablead.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/b/b2/Portrait_shanky.png -O assets/disco/Portrait_shanky.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/2/26/Portrait_siileng.png -O assets/disco/Portrait_siileng.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/d/d5/Portrait_sleeping_dockworker.png -O assets/disco/Portrait_sleeping_dockworker.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/0/00/Portrait_smoker.png -O assets/disco/Portrait_smoker.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/6/66/Portrait_soona.png -O assets/disco/Portrait_soona.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/1/11/Portrait_sponsor.png -O assets/disco/Portrait_sponsor.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/b/bd/Portrait_steban.png -O assets/disco/Portrait_steban.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/8/8a/Portrait_sylvie.png -O assets/disco/Portrait_sylvie.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/4/47/Portrait_theo.png -O assets/disco/Portrait_theo.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/8/8c/Portrait_titus.png -O assets/disco/Portrait_titus.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/2/28/Portrait_tiago.png -O assets/disco/Portrait_tiago.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/9/9d/Portrait_tommy.png -O assets/disco/Portrait_tommy.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/1/10/Portrait_Torson_v3.png -O assets/disco/Portrait_Torson_v3.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/5/57/Portrait_trant.png -O assets/disco/Portrait_trant.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/8/82/Portrait_washerwoman.png -O assets/disco/Portrait_washerwoman.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/3/3c/Portrait_waterlock.png -O assets/disco/Portrait_waterlock.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/5/54/Portrait_working-class-husband.png -O assets/disco/Portrait_working-class-husband.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/5/5f/Portrait_working-woman.png -O assets/disco/Portrait_working-woman.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/7/7b/Portrait_you_fash_nobeard.png -O assets/disco/Portrait_you_fash_nobeard.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/1/11/Portrait_you_fash.png -O assets/disco/Portrait_you_fash.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/4/4e/Portrait_you_nogrin_shaved.png -O assets/disco/Portrait_you_nogrin_shaved.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/4/40/Portrait_you_nogrin.png -O assets/disco/Portrait_you_nogrin.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/3/37/Portrait_you_obscured.png -O assets/disco/Portrait_you_obscured.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/c/c2/Portrait_you_shaved.png -O assets/disco/Portrait_you_shaved.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/8/83/Portrait_you.png -O assets/disco/Portrait_you.png
wget https://static.wikia.nocookie.net/discoelysium_gamepedia_en/images/9/95/TFC_portrait_little-lily.png -O assets/disco/TFC_portrait_little-lily.png